version: '3.8'

services:
  q-structurize:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: q-structurize
    ports:
      - "8878:8000"
    volumes:
      # Persist uploads
      - ./uploads:/app/uploads
      # Note: Models are built into the image during 'docker build'
      # No need to mount cache volumes as models persist in image layers
    environment:
      # Python settings
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      
      # Docling cache paths (must match where docling-tools downloads)
      - DOCLING_ARTIFACTS_PATH=/root/.cache/docling/models
      - HF_HOME=/app/.cache/huggingface
      
      # Tokenizers settings
      - TOKENIZERS_PARALLELISM=false
      
    # Restart policy
    restart: unless-stopped
    
    # Resource limits (optional, adjust as needed)
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2'
    
    # Health check
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
