services:
  q-structurize:
    build: .
    ports:
      - "8878:8000"
    volumes:
      - ./uploads:/app/uploads
      - ./cache:/app/.cache
      - ./cache:/root/.cache  # Also cache in root directory
    environment:
      - PYTHONPATH=/app
      - TRANSFORMERS_CACHE=/app/.cache/transformers
      - HF_HOME=/app/.cache/huggingface
      - TORCH_HOME=/app/.cache/torch
      - HF_HUB_CACHE=/app/.cache/huggingface
      - CUDA_VISIBLE_DEVICES=0
    restart: unless-stopped
    # GPU support disabled for macOS testing
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]
